== この活動について
以下のことに注意して、有意義な活動にできればと思ってます。 +

- 無理しなくていいです。強制要素は何もありません。
- 抜けるのも完全に自由です。
- チームに残り続けてROM（眺めるだけ）でも構いません。
- 健康を阻害してまでやる活動ではありません。
- メンバー間での活動の強制もやめましょう。
- 趣味レベル級にハマってきたら少し落ち着いてください。
- 睡眠時間を削ってまで活動を行わないでください。


== プロジェクトの構成
このプロジェクトの構成は以下のようになっています。 +
それぞれのプロジェクトの用途は抑えるようにしてください。

=== プロジェクトグループ
https://github.com/TraningManagementSystem

==== tms
「Training Management System」のアプリケーションリポジトリです。 +
アプリケーション資材はすべてこのリポジトリ内に入れることにしましょう。 +

===== docs
https://github.com/TraningManagementSystem/tms +
この資料は上記のURLで誰でも見れます。 +
隠す内容も何もないので、そのまま公開にしたいと思ってます。 +
 +
Training Management System で作成するドキュメントおよびをシステム構築するにあたりチームの決め事であったりノウハウの共有、
ハマりポイントなどを共有するガイドラインを記載するページです。後者に関してはグループソフトウェアやWikiをイメージしてもらえると良いかと。 +
以下が現時点で考えられているガイドラインです。

- ポリシー（活動ルール等）
- ローカル環境構築ガイドライン
- 設計ガイドライン
- 実装ガイドライン
- 単体テストガイドライン
- 結合テストガイドライン
- CI/CDガイドライン


[red]*あくまで公開範囲はインターネット上の全てということをお忘れなく。*

==== devlog
https://github.com/TraningManagementSystem/devlog +
システム開発ブログです。 +
必須ではありませんが、開発中に気になったことや調べて「ほぇ」と思ったことを書くと良いかと。 +
knowledgeはあくまで開発ルールの記載や手順の周知と言った内容ですが、devlogはゆるくて構いません。 +
なお、一発目はこんな感じのシステムが作れたらなぁと言った内容を投稿します。 +
 +
どちらかというと、日々のこの活動に対する不満とか、無茶振りだろこれ。 +
とかそういった愚痴を描いてもらう場でいいのかなぁとも思ってます。 +
どれだけこういったことを学ぶのに苦労するか、ということの心理的な感覚もそこから得られるので・・・ +
 +
[red]*あくまで公開範囲はインターネット上の全てということをお忘れなく。*

