== ドキュメントの書き方
:toc: left
:toclevel: 2
:toc-title: 目次
:figure-caption: 図
:table-caption: 表
:imagesdir: images
:homepage: https://traningmanagementsystem.github.io/devlog/

=== AsciiDocでのドキュメンテーションについて
このドキュメント自体がAsciiDocを用いて作成されていますが、この活動では全般的にOfficeの利用を廃止しています。
理由としては以下が挙げられます。

* GitHubを利用しているのでレビュー(Textでの比較)が行いたい
* ドキュメンテーションとして無駄な整形や番号振りといった作業をやめたい
* 1つの大きなドキュメントを分担して作成したい
* 複数人でドキュメントを作成しても統合するのは容易にしたい

最初のうちは、慣れないことが多くあるかと思いますが、
慣れたらこちらの方が圧倒的に楽になるはずです。（すみませんが、人によるので断言できません）


=== 文章の作成
AsciiDocを記述するにあたっていくつかの共通ルールを設けて、全員が守ることで最終成果物が綺麗になりますしレビューをするための前提条件にもなります。
命名するにあたり英単語に迷った場合は https://codic.jp/[codic] 等の辞書サイトを利用してもよい。

==== ドキュメントの配置場所
ドキュメントはプロジェクト内の`docs`ディレクトリへ集約します。
このディレクトリ配下の`public`ディレクトリが公開ディレクトリになります。
ディレクトリ構成は以下のようになります。

[source, text]
----
tms
 │
 ├─docs :ドキュメント
 │  │
 │  ├─public : ドキュメント公開ディレクトリ
 │  ├─Sec###_****
 │  │
 │  ├─index.html : ドキュメント公開ディレクトリのTOPページ
----


==== セクション名の命名ルール
セクションは、文章の区切りです。以下の命名ルールに沿って作成してください。

[option="header"]
|===

|命名ルール

|"Sec + セクション番号 + "_" + セクション内容を表すワード(任意)


|===


セクション番号::
セクション番号は、番号同士が近いと後々差し込むことができなくなるため、
ある程度の間を設けることにする。今回は最低でも「10」の幅を持たせるようにして下さい。



==== ファイルの命名ルール
AsciiDocは以下の命名ルールに沿って作成してください。

[option="header"]
|===

|命名ルール

|"Sec + セクション名 + "_" + ドキュメント内容を表すワード(任意) + ".adoc"


|===


==== テンプレートの利用
AsciiDocを記載するにあたり、
あらかじめ用意してあるテンプレートを利用して簡易に作成できます。
テンプレートは以下にありますのでコピーして利用してください。

[source]
----
tms/docs/template/template.adoc
----

設計書のフォーマットが定まってきたら、別途整理してテンプレート化をしていきましょう。


=== 図および画像の利用
図および画像を利用する場合は、各セクションディレクトリの配下にimagesというディレクトリを作成して
その中に図および画像のファイルを入れてください。
現在対応している拡張子は以下のみです。

.画像拡張子
[option="header"]
|====

|拡張子

|png
|jpg
|gif

|====

ファイル名は、以下の通りとします。


[option="header"]
|===

|命名ルール

|"Sec + セクション名 + "_" + ドキュメント内容を表すワード(任意) + "_" + 画像を表すワード(任意) + 画像拡張子


|===

=== 図の作成
図の作成には極力 http://plantuml.com/[PluntUML]を利用してください。
http://plantuml.com/[PluntUML]はシーケンス図、クラス図、コンポーネント図等を手早くテキストベースの
DSLで記述すると画像変換してくれる便利なツールです。 +
 +
テキストベースなので差分比較も行えます。
これ自体がレビュー対象になることはないかもしれませんが、後で見返した際にテキストで比較できることは大きいですし、
第三者による後続メンテナンスも楽になります。 +
 +
こちらも通常の画像と同様に各セクションディレクトリの配下にimagesというディレクトリを作成して
その中に図の元となる「puml」という拡張子のPluntUMLのDSLファイルと、変換後の画像ファイルを格納してください。
いくつかのテンプレートを用意していますので利用してください。
 +
[source]
----
tms/docs/template/images/template_sequence.adoc ：シーケンス用
tms/docs/template/images/template_usecase.adoc ：ユースケース用
----

いくつかの種類があるので、テンプレートにないものを作成した場合には、テンプレート化をしていきましょう。