= 規約
:toc: left
:toclevel: 2
:toc-title: 目次
:figure-caption: 図
:table-caption: 表
:imagesdir: images
:homepage: https://traningmanagementsystem.github.io/devlog/


== Overview
設計ガイドラインは本システムを構築するにあたって設計工程での決め事、留意しなければならない点を文章化し共有ことを目的としています。
そうすることで、スキルセットが異なる要員間での意識違い等を防ぎ成果物の品質を一定水準以上に保つことができると考えています。
開発中に記述に不足があったり、追加した方がよい内容があれば随時追記していくことを推奨・お願いします。

== 命名規約

=== 基本指針

==== 対象範囲
命名規約の対象範囲は、設計レベルに出現するワードまでとする。 +
プログラミングの内部での変数名の命名やその他雑多なものに関しては対象としない。 +
ただし、それぞれの対象範囲で細部までルール化されている場合は従うこと。 +
 +
例）プログラミングにおける命名規約はないが、コーディング規約中で別途指定されている場合は従う

==== 英単語の解決方法
日本語→英語の解決方法を１つにまとめることで混乱を防ぎます。 +
基本的にGoogle翻訳を利用してください。 +
Google翻訳はAPIが有料のため、無料のWebページのみ利用できます。

==== ワードの略語に関して
長い英単語を略してそれだけでは理解ができない文字列にすることは基本的に禁止する。 +
ただし、規定された桁数に当てはめたいなど理由がある場合には許容する。 +

==== 連番に関する注意点
何かしらの連番を割り振る場合には、ある程度の桁数を用意すること。 +
また、1の位を連番で繋げると後々修正や差し込みが行いにくくなるため
ある程度の範囲を拡張領域として用意しておくこと。+
 +
例）000 → 010 → 020


=== メッセージ関連

==== 画面メッセージID

==== ログメッセージID


=== データベース関連

==== sqlファイル
sqlファイルの名前に関しては、以下のような命名規則に従うこと。
```
V<メジャーバージョン＞.<マイナーバージョン>__<説明>.sql
```

例::
```
V1.0__Create_table.sql
```

* メジャーバージョン +
今回の開発では1で統一する。

* マイナーバージョン +
新たにsqlファイルを追加するときは、現在のマイナーバージョンから1バージョンを上げる

* 説明
sqlファイルの内容が分かる名前を英語でつける。 +
単語を区切る場合はアンダースコアを利用する。

CAUTION: マイナーバージョンと説明の間のアンダースコアは2つ必要であるので注意すること

=== パッケージ
