////
作成：2017/10/08
作成者：中村
////
= Knowledge - Gitの使い方
:toc: left
:toclevel: 2
:toc-title: 目次
:figure-caption: 図
:table-caption: 表
:imagesdir: images
:homepage: https://traningmanagementsystem.github.io/devlog/


== Overview
git初心者に向けてGitの使い方と説明をまとめていく。 +
gitのインストールが済んでいる前提である。 +
gitが入ってるかどうかはターミナルから

----
$ git --version
----
を打ちバージョン番号が表示されたらOK。$はコマンドプロンプトなのでコピペする必要はない。

== 超初心者向けのざっくりとした説明
[big]*addしてcommitしてpushするとgithubに変更が保存される。* +

↑がわかればとりあえずなんとか使えます。また、

[big]*編集作業を行う前に作業用のブランチに切り替えて編集する。*

という考えが重要です。masterブランチは成果物(提出用)なのでみんなで一斉にいじるのは良くないです。かならず作業用ブランチを作成し、作業用ブランチに切り替えてから作業を行いましょう。

[big]*実際の作業の流れは https://github.com/TraningManagementSystem/tms/blob/master/docs/Sec510_Dev_Policy/Sec510_Dev_Policy_howtowork.adoc[作業の進め方]を参照*

.ざっくりとした語句説明
[options="header",cols="1,3"]
|=================================
|語句       |説明
|add        |コミット前にコミットするファイルをインデックスにまとめておくこと。
|commit     | リポジトリに編集したファイルを登録すること。例)コミットしておけば「コミットログ4dcc22d3e4c1ca5dfc682b2b6ca1bebc3d65781dのファイルに戻す」とかできる。
|push       |リモートにリポジトリの状態を反映させる。今回はGithubにコミットしたものを反映させる。
|インデックス |コミットするためのファイルを書き込んでおくファイル。
|リポジトリ   | 「どのファイルがどんな変更でいつのコミットで登録された」みたいなのまるまる記録している場所のこと。
|ブランチ    |　『自分用の作業スペース』という感覚でOK。適当な名前のブランチを作成してそこで作業する。100人で開発するときmasterブランチを直接いじるのはマズイので。
|=================================


== Git初心者向けよく使うコマンドまとめと説明

=== プロジェクトのクローン
クローン⇒ファイルのダウンロードみたいなもの。変更履歴までまるまる持ってくきてくれる。 +
----
使い方
$ git clone 資材の置いてあるURL
例)
$ git clone https://github.com/TraningManagementSystem/knowledge.git
$ git clone https://github.com/TraningManagementSystem/tms.git
----

=== ファイルの更新(pull)
リモート(例:GitHub)にある最新ファイルをローカル(自分のPC)に持ってきて更新する。
----
$ git pull
----

==== 無理やりpullしてリモート先に合わせる
自分で編集を行っていた場合、そのファイルについてはpullで更新されない。
とにかくリモート先が正しいからそれに合わせたい。というときにリモート先と同じ状態にするには下記を実行。
----
$ git fetch origin
$ git reset --hard origin/ブランチ名

例）masterブランチと全く同じ状態にしたい
$ git fetch origin
$ git reset --hard origin/master
----

== ブランチの作成
----
$ git branch ブランチ名
----

== ブランチの切り替え
----
$ git checkout ブランチ名
----
* 編集したファイルがコミットしてない場合失敗します

[big]*開発は作業用ブランチに切り替えてからファイルを作成/修正しましょう*
----
■現在自分のいるブランチ名を確認
  $ git branch
■ブランチの作成
  $ git branch ブランチ名
■ブランチに切り替える
  $ git checkout ブランチ名
■ブランチをpushしてリモートに反映させる。
  $ git push origin ブランチ名
----



== 編集を破棄してむりやりブランチを切り替える
----
$ git checkout --force ブランチ名

■それでもうまく切りかえれないときはgit stashしてからchckoutする
$ git stash
----

=== ブランチの削除
削除するブランチにいるときはcheckoutでブランチを移動すること
----
■ローカルブランチの削除
  git branch -d ブランチ名
■リモートブランチの削除(2通り)
  git push origin :ブランチ名
  git push --delete origin ブランチ名


(削除の流れ)
■現在のブランチの確認
  $ git branch -r
■ブランチの変更(削除するブランチに居るときは適当な別のブランチに移動する。)
  $ git checkout 適当なブランチ名(masterでおｋ)
■ブランチの削除(ローカル)
  $ git branch -d 削除するブランチ名
■ブランチの確認
  $ git branch
■ブランチの削除(リモート)
  $ push origin :削除するブランチ名
----


=== ファイルの送信(push)
編集したローカルのファイルをリモート先に送信する。

=== pushの前準備(add,commit)
----
$ git add 編集したファイル名
$ git commit
----

viが起動するのでiで入力モードに +
コメント(何を修正したかを記入)を追加したら +
Escでコマンド入力モードへ +
:wqを押しエンター(wirte quitの意味) +

----
例)
$ git add --all
$ git commit -m コメン
----
* addの際-fで.gitignoreに書かれている管理対象外のファイルも強制的にadd。[big]*-fは使わないように！*
* --allで全てのをadd。
* -mでviエディタを開かずにコメント入力してコミットできる(””はいらない)

=== 送信(push)
----
$ git push　リポジトリ名 ブランチ名
(例)
$ git push origin master
----


==== addし忘れた時
addし忘れた！！というときに追加でaddしてコミットする。
----
$ git add hogehoge.txt
$ git commit --amend
----

=== コミットの取り消し
----
コミットの取り消し
■コミットのみの取り消し
$ git reset --soft HEAD^

■コミットとワーキングツリー(実際に編集してきたファイル)の戻し。前回コミットした段階までファイルも戻っちゃう。
$ git reset --hard HEAD^
----

=== git reset の取り消し(コミットの取り消しの取り消し)
----
現在のブランチの最新コミットを表すHEADに移動すればOK
$ git reset --soft HEAD
or
$ git reset --hard HEAD
----


=== ファイルのdiif(変更点の確認)
----
■add前のdiffをとるとき
$ git diff
■add後のdiffをとるとき
$ git diff -cached
■コミット後のdiffをとるとき
$ git diff HEAD^

■全体の変更点の確認(まだaddしてないファイル等を確認できたりする。addの際--all使うならあんまり使わないかも)
$ git status
----

* [big]*pushの前にdiffを取って変なファイルや変更をコミットしていないか確認する(推奨)*

== 特定のファイルを前のバージョンに戻す
----
$ git log で戻したいコミット番号を確認
$ git checkout コミット番号　戻したいファイル名
$ git add 戻したファイル名
$ git commit -m コメント
$ git push origin ブランチ名
----


=== リモートのファイルを削除
----
$ git rm 削除するファイル名
$ git commit -m コメント
$ git push origin ブランチ名
----

=== リモートのファイル名を変更
----
$ git mv ファイル名(変更前)　ファイル名(変更後)
$ git commit -m コメント
$ git push origin ブランチ名
----


=== タグの付与
タグ:: これもバージョンみたいなもの。

試験する毎にタグ切っておくと、このタグで試験しました！とか言える。
----
$ git tag -a -m "タグ名" タグ名
$ git push リポジトリ名 タグ名

(例)
$ git tag -a -m "V0.0.1" V0.0.1
$ git push origin V0.0.1
----

=== タグの削除
----
$ git tag -d タグ名
$ git push origin :refs/tags/タグ名
----




=== ユーザの設定
----
$ git config --global user.name "ユーザ名"
$ git config --global user.email 登録するメールアドレス
----

==== 設定の確認
ユーザ、リポジトリ名(デフォルト値origin)、ブランチ名(デフォルト値master)等が確認できる
----
$ git config --list
----
